{
  "comments": [
    {
      "unresolved": true,
      "key": {
        "uuid": "a6afd79f_f8714d88",
        "filename": "src/main/java/com/googlesource/gerrit/plugins/kinesis/CheckpointResetter.java",
        "patchSetId": 6
      },
      "lineNbr": 114,
      "author": {
        "id": 1005270
      },
      "writtenOn": "2021-03-31T12:39:46Z",
      "side": 1,
      "message": "wow do they throw exception with cause instead of just ResourceNotFoundException?",
      "range": {
        "startLine": 114,
        "startChar": 13,
        "endLine": 114,
        "endChar": 22
      },
      "revId": "801df0b5583b3bfa4101a1b589b18ad6efd73ae2",
      "serverId": "d5d70762-12d0-45a1-890d-524b12d3f735"
    }
  ]
}